### ISSUE TITLE
Keyboard Prefab

### ISSUE THREAD

**Issue by Kavex** [jetdog8808/JetDogs-Prefabs#3]
Did you know on your keyboard prefab you are missing the Q key? It's listed as another A
![2019-12-30_16-58-31](https://user-images.githubusercontent.com/5668221/71606050-0c68bc00-2b2b-11ea-9861-be8350160cb9.png)

**Comment by jetdog8808** [comment]
I wont be updating my prefabs till vrchat updates to 2018 unity. to fix the problem you will need to change two string variables. 
![image](https://user-images.githubusercontent.com/36026251/71706040-295df300-2da8-11ea-8c15-3025c491895f.png)

the first object labeled text you will change to "q" for the visual key.
![image](https://user-images.githubusercontent.com/36026251/71706113-91acd480-2da8-11ea-9568-13c0edaf8408.png)

next is the button event. changing the string in the button events to a "q" so that it will be appended to the input field.
![image](https://user-images.githubusercontent.com/36026251/71706165-cc167180-2da8-11ea-8f8f-9096a1e66bdd.png)

**Comment by jetdog8808** [comment]
the changes have been made to the prefabs and will be uploaded when ever vrchat unity 2018 comes out.
